In [1]:
!pip install numpy


In [ ]:
import numpy as np
import random

In [ ]:
a = np.array([1,2,3])

b = np.array([1,'a',2])
# Matrix toutes élément zéros
c = np.zeros((3,4))
# Matrix identifié 
d = np.eye(3)


In [7]:
print (a,'\n',b,'\n',c,'\n',d)


[1 2 3] 
 ['1' 'a' '2'] 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Numpy with law of Probability

In [13]:
s = np.random.uniform(0,1,1000)
s


array([0.11896638, 0.90875719, 0.1602369 , 0.52059786, 0.63522948,
       0.29579741, 0.96581211, 0.28945577, 0.18047077, 0.54634175,
       0.56471987, 0.28913796, 0.0382685 , 0.71599532, 0.03887008,
       0.58107654, 0.36419469, 0.95938788, 0.02298141, 0.19996121,
       0.22363032, 0.67457589, 0.48372294, 0.09631538, 0.82596098,
       0.29856901, 0.88412869, 0.18849215, 0.99618864, 0.37646192,
       0.92693174, 0.17731951, 0.65219857, 0.37354958, 0.95837705,
       0.63630475, 0.36913021, 0.38875676, 0.58956998, 0.99551539,
       0.75529417, 0.76102345, 0.95259383, 0.35257324, 0.69569138,
       0.33546983, 0.35944837, 0.25817961, 0.01633396, 0.9184971 ,
       0.83766641, 0.27033029, 0.38083941, 0.07423975, 0.41229303,
       0.04166883, 0.33572553, 0.40469237, 0.86942335, 0.46328023,
       0.22452038, 0.16744673, 0.34950721, 0.27327941, 0.83430568,
       0.89585468, 0.72608698, 0.99521751, 0.8669843 , 0.1495783 ,
       0.54521534, 0.34378583, 0.5696535 , 0.17445897, 0.25137

In [ ]:
rng = np.random.default_rng(seed=12345)
rng.uniform(0,1)
rng.uniform(size = 1000)

array([3.16758340e-01, 7.97365457e-01, 6.76254671e-01, 3.91109551e-01,
       3.32813928e-01, 5.98308754e-01, 1.86734186e-01, 6.72756044e-01,
       9.41802865e-01, 2.48245715e-01, 9.48881152e-01, 6.67237453e-01,
       9.58979356e-02, 4.41839666e-01, 8.86479919e-01, 6.97453500e-01,
       3.26472864e-01, 7.33928163e-01, 2.20134956e-01, 8.15945695e-02,
       1.59895601e-01, 3.40100185e-01, 4.65193154e-01, 2.66421028e-01,
       8.15776403e-01, 1.93294389e-01, 1.29469076e-01, 9.16647515e-02,
       5.98568014e-01, 8.54741904e-01, 6.01621242e-01, 9.31988361e-01,
       7.24781361e-01, 8.60551317e-01, 9.29337802e-01, 5.46186009e-01,
       9.37672959e-01, 4.94987940e-01, 2.73773182e-01, 4.51778707e-01,
       6.65038923e-01, 3.30890930e-01, 9.03454007e-01, 2.57074175e-01,
       3.39828338e-01, 2.58853399e-01, 3.55446480e-01, 5.02233372e-03,
       6.28604544e-01, 2.82382707e-01, 6.80876895e-02, 6.16828977e-01,
       1.76326320e-01, 3.04388387e-01, 4.40886811e-01, 1.50202341e-01,
      

In [ ]:
normal = np.random.normal(0,2, size= 20)
normal


array([ 3.05813341, -0.078658  , -2.00260982,  1.96784782, -2.59761731,
        1.84718981,  1.19158791, -2.17578555,  1.37016265,  1.90616863,
        0.670943  , -2.34603525,  0.35320112, -2.5653766 ,  2.55611398,
       -1.16890051, -6.22235538, -2.25570911, -1.15450859, -0.80128116])

## Slicing python  
### method = lst[first_position,end_position,step]


In [22]:
lst = [1,2,3,4,7,9]
print(lst[4:-1])
print(lst[2:5:1])


[7]
[3, 4, 7]


In [32]:
x1 = np.arange(10)
print(x1[1:6:2],x1)
print(x1[0:10:2], 'ou', x1[::2]) 
print(x1[1:len(x1)])
print(x1[0:5], 'ou', x1[:5])

[1 3 5] [0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8] ou [0 2 4 6 8]
[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] ou [0 1 2 3 4]


### Matrix

In [33]:
x = np.array([[1,2,3],[4,5,6]], np.int32)
x[1,2]

np.int32(6)

In [ ]:
print(x[:,2]) # print deuxieme colonne du matrix x

[3 6]


In [48]:
x = np.arange(10)
x2 = np.array([[-1,1,-2],[-3,2,0]])
print(x)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[[-1  1 -2]
 [-3  2  0]]


In [ ]:
x == 2 # Comparer les element dans le matrix avec 2 

array([False, False,  True, False, False, False, False, False, False,
       False])

In [45]:
x2 < 0


array([[ True, False, False],
       [ True, False, False]])

In [49]:
x2[x2==-2]

array([-2])

In [ ]:
x = np.random.normal(size=10000)
print(f"{len(x[np.abs(x) > 1.96])/len(x):0.2%}")


4.94%


In [64]:
# Assuming rng has been created beforehand
x = rng.normal(0, size=(3, 4))
y = np.array([np.nan, 0, 1])

print(f"Count_zero: {np.count_nonzero(y)}")

Count_zero: 2
